auto RI::serialize(serializer& s) -> void {
  s(io.operatingMode);
  s(io.stopT);
  s(io.stopR);
  s(io.CCtlI);
  s(io.CCtlEn);
  s(io.rxSelect);
  s(io.txSelect);
  s(io.refreshDelayClean);
  s(io.refreshDelayDirty);
  s(io.refreshBank);
  s(io.refreshEnable);
  s(io.refreshOptimize);
  s(io.refreshMultibank);
  s(io.latency);
  s(io.ackErr);
  s(io.nackErr);
  s(io.overRangeErr);
  s(io.banksValid);
  s(io.banksDirty);
}
